##############################################
#
# Name: Enterprise_Basis.sql
#
# Author: Peter Christen
#
# Version: 1.0
#
# Date: 10.01.2021
#
# Purpose: Tabelle und Daten für Beispiel StarTrek
#
##############################################

#Inhalt Tabelle
#Nr.,"Titel",Jahr,Kosten,"Raumschiff","Captain","Erster Offizier","Navigation","Steuerung","Chefingenieur","Medizin. Offizier")

drop table if exists StarTrek;
create table StarTrek(
    id int primary key auto_increment,
    Titel varchar(40),
    Jahr int,
    Kosten int,
    Raumschiff varchar(30),
    Captain varchar(30),
    ErsterOffizier varchar(30),
    Navigation varchar(30),
    Steuerung varchar(30),
    Chefingenieur varchar(30),
    MedOffizier varchar(30));

insert into StarTrek values(1,"Star Trek: Der Film",1979,35,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(2,"Der Zorn des Khan",1982,11,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(3,"Auf der Suche nach Mr. Spock",1984,17,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(4,"Zurück in die Gegenwart",1986,25,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(5,"Am Rande des Universums",1989,30,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(6,"Das unentdeckte Land",1991,30,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(7,"Treffen der Generationen",1994,35,"USS Enterprise NCC-1701-E","Jean-Luc Picard","William T. Riker","Ro Laren","Wesley Crusher","Geordi LaForge","Dr. Beverly Crusher");
insert into StarTrek values(8,"Der erste Kontakt",1996,45,"USS Enterprise NCC-1701-E","Jean-Luc Picard","William T. Riker","Ro Laren","Wesley Crusher","Geordi LaForge","Dr. Beverly Crusher");
insert into StarTrek values(9,"Der Aufstand",1998,58,"USS Enterprise NCC-1701-E","Jean-Luc Picard","William T. Riker","Ro Laren","Wesley Crusher","Geordi LaForge","Dr. Beverly Crusher");
insert into StarTrek values(10,"Nemesis",2002,60,"USS Enterprise NCC-1701-E","Jean-Luc Picard","William T. Riker","Ro Laren","Wesley Crusher","Geordi LaForge","Dr. Beverly Crusher");
insert into StarTrek values(11,"Star Trek",2009,150,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(12,"Into Darkness",2013,190,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");
insert into StarTrek values(13,"Beyond",2016,185,"USS Enterprise NCC-1701","James T. Kirk","Spock","Hikaru Sulu","Pavel Chekov","Montgomery Scott","Dr. Leonard McCoy");

drop table if exists StarTrek_Schiffe;
create table StarTrek_Schiffe(
    schiff_id int primary key auto_increment,
    Raumschiff varchar(50),
    Registrierung varchar(30),
    Klasse varchar(40));

insert into StarTrek_Schiffe values(1,"USS Adelphi","Unknown","Unknown");
insert into StarTrek_Schiffe values(2,"USS Agamemnon","Unknown","Unknown");
insert into StarTrek_Schiffe values(3,"USS Ahwahnee","NCC-2048","Constitution-class");
insert into StarTrek_Schiffe values(4,"USS Ahwahnee","NCC-71620","Cheyenne-class");
insert into StarTrek_Schiffe values(5,"USS Ajax","NCC-11574","Apollo-class");
insert into StarTrek_Schiffe values(6,"USS Akagi","NCC-62158","Unknown");
insert into StarTrek_Schiffe values(7,"USS Al-Batani","Unknown","Unknown");
insert into StarTrek_Schiffe values(8,"USS Albert Einstein","NCC-85183","Unknown");
insert into StarTrek_Schiffe values(9,"USS Aleo","NCC-1981","Unknown");
insert into StarTrek_Schiffe values(10,"USS Alka-Selsior","NCC-1404","Alka-Selsior-type");
insert into StarTrek_Schiffe values(11,"USS Alhambra","unknown","California-class");
insert into StarTrek_Schiffe values(12,"Antares","NCC-501","Antares-type");
insert into StarTrek_Schiffe values(13,"USS Antares","NCC-9844","Miranda-class");
insert into StarTrek_Schiffe values(14,"USS Apollo","NCC-30000","Unknown");
insert into StarTrek_Schiffe values(15,"USS Appalachia","NCC-52136","Steamrunner-class");
insert into StarTrek_Schiffe values(16,"USS Archer","NCC-44278","Unknown");
insert into StarTrek_Schiffe values(17,"Archon","Unknown","Unknown");
insert into StarTrek_Schiffe values(18,"Arcos","Unknown","Antares-class");
insert into StarTrek_Schiffe values(19,"USS Ariel","Unknown","Survey/Science ship");
insert into StarTrek_Schiffe values(20,"USS Aries","NCC-45167","Renaissance-class");
insert into StarTrek_Schiffe values(21,"USS Armstrong","NCC-1769","Armstrong-type");
insert into StarTrek_Schiffe values(22,"USS Armstrong","NCC-317659","Armstrong-type");
insert into StarTrek_Schiffe values(23,"SS Artemis","Unknown","Colony ship");
insert into StarTrek_Schiffe values(24,"USS Aryabhatta","Unknown","Unknown");
insert into StarTrek_Schiffe values(25,"Astral Queen","Unknown","Transport");
insert into StarTrek_Schiffe values(26,"USS Atlantis","NCC-32710","Unknown");
insert into StarTrek_Schiffe values(27,"SS Augyn","NGA-24858","Transport");
insert into StarTrek_Schiffe values(28,"Aurora","NC-17740","Class J starship");
insert into StarTrek_Schiffe values(29,"B-24-CLN","Unknown","Unknown");
insert into StarTrek_Schiffe values(30,"USS Baton Rouge","Unknown","Unknown");
insert into StarTrek_Schiffe values(31,"SS Beagle","Unknown","Class 4 stardrive vessel");
insert into StarTrek_Schiffe values(32,"USS Bellerophon","NCC-62048","Nebula-class");
insert into StarTrek_Schiffe values(33,"USS Bellerophon","NCC-74705","Intrepid-class");
insert into StarTrek_Schiffe values(34,"USS Berlin","NCC-14232","Excelsior-class");
insert into StarTrek_Schiffe values(35,"USS Biddeford","NCC-0718","Newton-type");
insert into StarTrek_Schiffe values(36,"USS Biko","Unknown","Oberth-class");
insert into StarTrek_Schiffe values(37,"USS Billings","Unknown","Unknown");
insert into StarTrek_Schiffe values(38,"Bonaventure","10281NCC","Unknown");
insert into StarTrek_Schiffe values(39,"USS Bonchune","NCC-70915","Nebula-class");
insert into StarTrek_Schiffe values(40,"USS Bonestell","NCC-31600","Oberth-class");
insert into StarTrek_Schiffe values(41,"USS Bouman","Unknown","Unknown");
insert into StarTrek_Schiffe values(42,"HMS Bounty","Unknown","Klingon Bird-of-Prey");
insert into StarTrek_Schiffe values(43,"USS Bozeman","NCC-1941","Soyuz-class");
insert into StarTrek_Schiffe values(44,"USS Bradbury","NX-72307","Bradbury-class");
insert into StarTrek_Schiffe values(45,"USS Brattain","NCC-21166","Miranda-class");
insert into StarTrek_Schiffe values(46,"USS Budapest","NCC-64923","Norway-class");
insert into StarTrek_Schiffe values(47,"USS Buran","NCC-57580","Challenger-class");
insert into StarTrek_Schiffe values(48,"USS Cairo","Unknown","Excelsior-class");
insert into StarTrek_Schiffe values(49,"USS Callisto","Unknown","Unknown");
insert into StarTrek_Schiffe values(50,"USS Carolina","Unknown","Unknown");
insert into StarTrek_Schiffe values(51,"USS Centaur","NCC-42043","Centaur-type");
insert into StarTrek_Schiffe values(52,"USS Cerritos","NCC-75567","California-class");
insert into StarTrek_Schiffe values(53,"USS Challenger","NCC-71099","Galaxy-class");
insert into StarTrek_Schiffe values(54,"USS Charleston","NCC-42285","Excelsior-class");
insert into StarTrek_Schiffe values(55,"USS Chatelet","Unknown","Unknown");
insert into StarTrek_Schiffe values(56,"USS Chekov","NCC-57302","Springfield-class");
insert into StarTrek_Schiffe values(57,"USS Chicago","Unknown","Unknown");
insert into StarTrek_Schiffe values(58,"USS Clarke","NCC-1661","Malachowski-class");
insert into StarTrek_Schiffe values(59,"USS Clavyn","Unknown","Unknown");
insert into StarTrek_Schiffe values(60,"USS Clayton","Unknown","Unknown");
insert into StarTrek_Schiffe values(61,"USS Clement","NCC-12537","Unknown");
insert into StarTrek_Schiffe values(62,"USS Cochrane","NCC-59318","Oberth-class");
insert into StarTrek_Schiffe values(63,"USS Coleman","Unknown","Unknown");
insert into StarTrek_Schiffe values(64,"Coloma","Unknown","Mining vessel");
insert into StarTrek_Schiffe values(65,"SS Columbia","NC-5940-1","Survey ship");
insert into StarTrek_Schiffe values(66,"USS Columbia","NCC-621","Scout");
insert into StarTrek_Schiffe values(67,"USS Concord","Unknown","Unknown");
insert into StarTrek_Schiffe values(68,"USS Constantinople","NCC-43622","Transport ship");
insert into StarTrek_Schiffe values(69,"USS Constellation","NCC-1017","Constitution-class");
insert into StarTrek_Schiffe values(70,"USS Cooper","Unknown","Unknown");
insert into StarTrek_Schiffe values(71,"USS Copernicus","NCC-640","Oberth-class");
insert into StarTrek_Schiffe values(72,"USS Cortez","Unknown","Unknown");
insert into StarTrek_Schiffe values(73,"USS Crazy Horse","Unknown","Excelsior-class");
insert into StarTrek_Schiffe values(74,"USS Crockett","Unknown","Unknown");
insert into StarTrek_Schiffe values(75,"USS Curry","NCC-42254","Curry-type");
insert into StarTrek_Schiffe values(76,"USS Cuyahoga","Unknown","Unknown");
insert into StarTrek_Schiffe values(77,"USS Da-Teplan","NCC-30087","Unknown");
insert into StarTrek_Schiffe values(78,"USS Dana","Unknown","Hoover-class");
insert into StarTrek_Schiffe values(79,"USS De Milo","Unknown","Hoover-class");
insert into StarTrek_Schiffe values(80,"USS Defiant","NCC-1764","Constitution-class");
insert into StarTrek_Schiffe values(81,"USS Denver","Unknown","Transport");
insert into StarTrek_Schiffe values(82,"USS Destiny","Unknown","Unknown");
insert into StarTrek_Schiffe values(83,"Diana","Unknown","Unknown");
insert into StarTrek_Schiffe values(84,"SS Dierdre","Unknown","Freighter");
insert into StarTrek_Schiffe values(85,"USS Discovery","NCC-1031","Crossfield-class");
insert into StarTrek_Schiffe values(86,"USS Donovan","Unknown","Unknown");
insert into StarTrek_Schiffe values(87,"USS Drake","Unknown","Unknown");
insert into StarTrek_Schiffe values(88,"USS Eagle","NCC-956","Constitution-class");
insert into StarTrek_Schiffe values(89,"DEV Eagle Valley","Unknown","DY-950");
insert into StarTrek_Schiffe values(90,"USS Earhart","Engle-class","Unknown");
insert into StarTrek_Schiffe values(91,"USS Edison","NCC-1683","Hoover-class");
insert into StarTrek_Schiffe values(92,"USS Elkins","NCC-74121","Elkins-type");
insert into StarTrek_Schiffe values(93,"USS Emden","NCC-1856","Constitution-class");
insert into StarTrek_Schiffe values(94,"USS Endeavour","NCC-1895","Constitution-class");
insert into StarTrek_Schiffe values(95,"USS Entente","NCC-2120","Dreadnought");
insert into StarTrek_Schiffe values(96,"USS Enterprise","NCC-1701","Constitution-class");
insert into StarTrek_Schiffe values(97,"USS Enterprise","NCC-1701-A","Constitution-class");
insert into StarTrek_Schiffe values(98,"USS Enterprise","NCC-1701-A","Constitution-class refit");
insert into StarTrek_Schiffe values(99,"USS Enterprise","NCC-1701-B","Excelsior-class refit");
insert into StarTrek_Schiffe values(100,"USS Enterprise","NCC-1701-C","Ambassador-class");
insert into StarTrek_Schiffe values(101,"USS Enterprise","NCC-1701-D","Galaxy-class");
insert into StarTrek_Schiffe values(102,"USS Enterprise","NCC-1701-E","Sovereign-class");
insert into StarTrek_Schiffe values(103,"USS Enterprise","NCC-1701-J","Universe-class");
insert into StarTrek_Schiffe values(104,"USS Equicon","NCC-1988","Unknown");
insert into StarTrek_Schiffe values(105,"USS Equinox","NCC-72381","Nova-class");
insert into StarTrek_Schiffe values(106,"USS Essex","NCC-173","Daedalus-class");
insert into StarTrek_Schiffe values(107,"USS Europa","NCC-1648","Nimitz-class");
insert into StarTrek_Schiffe values(108,"USS Excalibur","NCC-1664","Constitution-class");
insert into StarTrek_Schiffe values(109,"USS Excalibur","NCC-26517","Ambassador-class");
insert into StarTrek_Schiffe values(110,"USS Excelsior","NCC-2000","Excelsior-class");
insert into StarTrek_Schiffe values(111,"USS Excelsior","NCC-21445","Unknown");
insert into StarTrek_Schiffe values(112,"USS Exeter","NCC-1672","Constitution-class");
insert into StarTrek_Schiffe values(113,"USS Farouk El-Baz","NCC-31823","Unknown");
insert into StarTrek_Schiffe values(114,"USS Farragut","NCC-60597","Nebula-class");
insert into StarTrek_Schiffe values(115,"USS Fearless","NCC-14598","Excelsior-class");
insert into StarTrek_Schiffe values(116,"The Festoon","Unknown","Transport");
insert into StarTrek_Schiffe values(117,"USS Firebrand","NCC-68723","Freedom-class");
insert into StarTrek_Schiffe values(118,"Fleming","Unknown","Medical transport");
insert into StarTrek_Schiffe values(119,"Foresight","Unknown","Civilian emergency transport");
insert into StarTrek_Schiffe values(120,"USS Franklin","NX-326","Freedom-class");
insert into StarTrek_Schiffe values(121,"USS Fredrickson","NCC-42111","Excelsior-class");
insert into StarTrek_Schiffe values(122,"USS Gagarin","NCC-1309","Shepard-class");
insert into StarTrek_Schiffe values(123,"USS Galaxy","NCC-70637","Galaxy-class");
insert into StarTrek_Schiffe values(124,"USS Gallico","Unknown","Unknown");
insert into StarTrek_Schiffe values(125,"USS Gander","Unknown","Danube-class");
insert into StarTrek_Schiffe values(126,"USS Gandhi","Unknown","Unknown");
insert into StarTrek_Schiffe values(127,"USS Ganges","NCC-72454","Danube-class");
insert into StarTrek_Schiffe values(128,"USS Ganymede","NCC-18451","Unknown");
insert into StarTrek_Schiffe values(129,"USS Gettysburg","Unknown","Unknown");
insert into StarTrek_Schiffe values(130,"USS Glenn","NCC-1030","Crossfield-class");
insert into StarTrek_Schiffe values(131,"USS Goddard","NCC-59621","Korolev-class");
insert into StarTrek_Schiffe values(132,"USS Gorkon","Unknown","Excelsior-class");
insert into StarTrek_Schiffe values(133,"USS Gremlin","NCC-72927","Unknown");
insert into StarTrek_Schiffe values(134,"USS Greyhound","Unknown","Unknown");
insert into StarTrek_Schiffe values(135,"USS Grissom","NCC-638","Oberth-class");
insert into StarTrek_Schiffe values(136,"USS Hathaway","NCC-2593","Constellation-class");
insert into StarTrek_Schiffe values(137,"SS Hatteras","Unknown","DY-245");
insert into StarTrek_Schiffe values(138,"Havana","Unknown","Unknown");
insert into StarTrek_Schiffe values(139,"USS Heart of Gold","NCC-42","Unknown");
insert into StarTrek_Schiffe values(140,"USS Helin","NCC-1692","Unknown");
insert into StarTrek_Schiffe values(141,"USS Hera","Unknown","Unknown");
insert into StarTrek_Schiffe values(142,"USS Hermes","NCC-10376","Unknown");
insert into StarTrek_Schiffe values(143,"USS Hiawatha","NCC-815","Hiawatha-type");
insert into StarTrek_Schiffe values(144,"USS Hiraga Gennai","Unknown","Unknown");
insert into StarTrek_Schiffe values(145,"USS Hispaniola","Unknown","Unknown");
insert into StarTrek_Schiffe values(146,"USS Honshu","NCC-60205","Nebula-class");
insert into StarTrek_Schiffe values(147,"USS Hood","NCC-1703","Constitution-class");
insert into StarTrek_Schiffe values(148,"USS Hood","NCC-42296","Excelsior-class");
insert into StarTrek_Schiffe values(149,"USS Hoover","Unknown","Hoover-class");
insert into StarTrek_Schiffe values(150,"USS Horatio","Unknown","Ambassador-class");
insert into StarTrek_Schiffe values(151,"USS Horizon","NCC-176","Daedalus-class");
insert into StarTrek_Schiffe values(152,"USS Hornet","NCC-45231","Unknown");
insert into StarTrek_Schiffe values(153,"USS Huron","NCC-F1913","Huron-type");
insert into StarTrek_Schiffe values(154,"USS ibn Majid","NCC-75710","Curiosity-class");
insert into StarTrek_Schiffe values(155,"USS Illinois","Unknown","Unknown");
insert into StarTrek_Schiffe values(156,"USS Intrepid","NCC-1631","Constitution-class");
insert into StarTrek_Schiffe values(157,"USS James Fennimore Cooper","NCC-4077","Unknown");
insert into StarTrek_Schiffe values(158,"USS Jenolan","NCC-2010","Sydney-class");
insert into StarTrek_Schiffe values(159,"USS John Muir","NCC-1732","Unknown");
insert into StarTrek_Schiffe values(160,"Kearsarge","Unknown","Unknown");
insert into StarTrek_Schiffe values(161,"USS Kelvin","NCC-0514","Kelvin-type");
insert into StarTrek_Schiffe values(162,"USS Kerala","NCC-1255","Shepard-class");
insert into StarTrek_Schiffe values(163,"SS Kogin","NAR-24016","Transport");
insert into StarTrek_Schiffe values(164,"USS Kongo","NCC-1710","Unknown");
insert into StarTrek_Schiffe values(165,"USS Korolev","NCC-2014","Constitution-class");
insert into StarTrek_Schiffe values(166,"USS Kyushu","NCC-65491","New Orleans-class");
insert into StarTrek_Schiffe values(167,"USS Lakota","NCC-42768","Excelsior-class");
insert into StarTrek_Schiffe values(168,"SS Lakul","NFT-7793","Whorfin-class");
insert into StarTrek_Schiffe values(169,"USS Lalo","Unknown","Unknown");
insert into StarTrek_Schiffe values(170,"USS Lantree","NCC-1837","Miranda-class");
insert into StarTrek_Schiffe values(171,"LaSalle","Unknown","Unknown");
insert into StarTrek_Schiffe values(172,"USS Leeds","NCC-70352","Nebula-class");
insert into StarTrek_Schiffe values(173,"USS Leondegrance","NCC-2176","Cruiser");
insert into StarTrek_Schiffe values(174,"USS Lexington","NCC-1709","Constitution-class");
insert into StarTrek_Schiffe values(175,"USS Lexington","NCC-30405","Nebula-class");
insert into StarTrek_Schiffe values(176,"USS Liberator","NCC-67016","Unknown");
insert into StarTrek_Schiffe values(177,"USS Livingston","Unknown","Unknown");
insert into StarTrek_Schiffe values(178,"USS Madison","Unknown","Unknown");
insert into StarTrek_Schiffe values(179,"USS Magellan","Unknown","Unknown");
insert into StarTrek_Schiffe values(180,"USS Majestic","NCC-31060","Miranda-class");
insert into StarTrek_Schiffe values(181,"USS Malinche","Unknown","Excelsior-class");
insert into StarTrek_Schiffe values(182,"USS Malone","Unknown","Unknown");
insert into StarTrek_Schiffe values(183,"SS Manila","NGA-20124","Transport");
insert into StarTrek_Schiffe values(184,"SS Manoa","NAR-28474","Transport");
insert into StarTrek_Schiffe values(185,"USS Mare Tranquillitatis","Unknown","Unknown");
insert into StarTrek_Schiffe values(186,"USS Maryland","Unknown","Unknown");
insert into StarTrek_Schiffe values(187,"USS Matte Fringe","NCC-12898","Unknown");
insert into StarTrek_Schiffe values(188,"USS Max Plank","NCC-28573","Unknown");
insert into StarTrek_Schiffe values(189,"USS Mayflower","NCC-1621","Mayflower-type");
insert into StarTrek_Schiffe values(190,"USS Mekong","Unknown","Danube-class");
insert into StarTrek_Schiffe values(191,"USS Melbourne","NCC-62043","Excelsior-class");
insert into StarTrek_Schiffe values(192,"USS Merced","NCC-87075","California-class");
insert into StarTrek_Schiffe values(193,"USS Merrimac","NCC-1715","Cruiser");
insert into StarTrek_Schiffe values(194,"USS Merrimac","NCC-61827","Nebula-class");
insert into StarTrek_Schiffe values(195,"Milan","Unknown","Unknown");
insert into StarTrek_Schiffe values(196,"USS Minnow","NCC-19585","Unknown");
insert into StarTrek_Schiffe values(197,"SS Molokai","Unknown","Unknown");
insert into StarTrek_Schiffe values(198,"USS Monitor","NCC-61826","Nebula-class");
insert into StarTrek_Schiffe values(199,"USS Muleskinner","Unknown","Unknown");
insert into StarTrek_Schiffe values(200,"USS Muroc","Unknown","Unknown");
insert into StarTrek_Schiffe values(201,"USS Musashi","Unknown","Unknown");
insert into StarTrek_Schiffe values(202,"USS Mustang","NCC-85343","Unknown");
insert into StarTrek_Schiffe values(203,"USS Nash","NCC-2010-5","Sydney-class");
insert into StarTrek_Schiffe values(204,"USS Nautilus","NCC-31910","Miranda-class");
insert into StarTrek_Schiffe values(205,"USS Neil Armstrong","NCC-31806","Unknown");
insert into StarTrek_Schiffe values(206,"USS Newton","NCC-1727","Newton-type");
insert into StarTrek_Schiffe values(207,"USS Niels Bohr","Unknown","Unknown");
insert into StarTrek_Schiffe values(208,"Nightingale","Unknown","Wallenberg-class");
insert into StarTrek_Schiffe values(209,"USS Nightwing","NCC-8342","Unknown");
insert into StarTrek_Schiffe values(210,"USS Nobel","NCC-55012","Unknown");
insert into StarTrek_Schiffe values(211,"USS Nog","NCC-325070","Eisenberg-class");
insert into StarTrek_Schiffe values(212,"USS Non Sequitur","NCC-12999","Unknown");
insert into StarTrek_Schiffe values(213,"Norkova","Unknown","Antares-class");
insert into StarTrek_Schiffe values(214,"USS Northridge","Unknown","Unknown");
insert into StarTrek_Schiffe values(215,"USS Nova","NCC-73515","Unknown");
insert into StarTrek_Schiffe values(216,"USS Oakland","Unknown","Unknown");
insert into StarTrek_Schiffe values(217,"USS Oberth","NCC-602","Oberth-class");
insert into StarTrek_Schiffe values(218,"Odin","Unknown","Freighter");
insert into StarTrek_Schiffe values(219,"USS Odyssey","NCC-71832","Galaxy-class");
insert into StarTrek_Schiffe values(220,"USS Okinawa","Unknown","Unknown");
insert into StarTrek_Schiffe values(221,"USS Olympia","Unknown","Unknown");
insert into StarTrek_Schiffe values(222,"USS Omaha Nebraska","NCC-5252","Unknown");
insert into StarTrek_Schiffe values(223,"USS Orinoco","NCC-72905","Danube-class");
insert into StarTrek_Schiffe values(224,"Osler","NX-75300","Osler-type");
insert into StarTrek_Schiffe values(225,"USS Pasteur","NCC-58925","Olympic-class");
insert into StarTrek_Schiffe values(226,"USS Pegasus","NCC-53847","Oberth-class");
insert into StarTrek_Schiffe values(227,"USS Philadelphia","Unknown","Unknown");
insert into StarTrek_Schiffe values(228,"USS Peterson","Unknown","Unknown");
insert into StarTrek_Schiffe values(229,"USS Phoenix","NCC-65420","Nebula-class");
insert into StarTrek_Schiffe values(230,"USS Portland","Unknown","Unknown");
insert into StarTrek_Schiffe values(231,"USS Potemkin","NCC-1657","Constitution-class");
insert into StarTrek_Schiffe values(232,"USS Princeton","NCC-59804","Unknown");
insert into StarTrek_Schiffe values(233,"USS Prokofiev","Unknown","Unknown");
insert into StarTrek_Schiffe values(234,"USS Prometheus","NCC-71201","Nebula-class");
insert into StarTrek_Schiffe values(235,"USS Prometheus","NX-59650","Prometheus-class");
insert into StarTrek_Schiffe values(236,"USS Proxima","Unknown","Unknown");
insert into StarTrek_Schiffe values(237,"USS Pueblo","Unknown","Unknown");
insert into StarTrek_Schiffe values(238,"USS Quiele","Unknown","Unknown");
insert into StarTrek_Schiffe values(239,"USS Quito","Unknown","Unknown");
insert into StarTrek_Schiffe values(240,"Raging Queen","NCC-42284","Curry-type");
insert into StarTrek_Schiffe values(241,"USS Raman","NCC-29487","Science vessel");
insert into StarTrek_Schiffe values(242,"USS Raven","NAR-32450","Raven-type");
insert into StarTrek_Schiffe values(243,"USS Relativity","NCV-474439-G","Wells-class");
insert into StarTrek_Schiffe values(244,"USS Reliant","NCC-1864","Miranda-class");
insert into StarTrek_Schiffe values(245,"USS Renegade","Unknown","Frigate");
insert into StarTrek_Schiffe values(246,"USS Republic","NCC-1371","Unknown");
insert into StarTrek_Schiffe values(247,"USS Repulse","NCC-2544","Excelsior-class");
insert into StarTrek_Schiffe values(248,"USS Revere","NCC-595","Scout");
insert into StarTrek_Schiffe values(249,"USS Rhode Island","NCC-72701","Nova-class");
insert into StarTrek_Schiffe values(250,"USS Ride","Unknown","Shepard-class");
insert into StarTrek_Schiffe values(251,"USS Rio Grande","NCC-72452","Danube-class");
insert into StarTrek_Schiffe values(252,"SS Robert Fox","NFT-1327","Whorfin-class");
insert into StarTrek_Schiffe values(253,"USS Robert Louis Stevenson","NCC-1281","Unknown");
insert into StarTrek_Schiffe values(254,"USS Roosevelt","Unknown","Unknown");
insert into StarTrek_Schiffe values(255,"USS Rubicon","NCC-72936","Danube-class");
insert into StarTrek_Schiffe values(256,"USS Rubidoux","NCC-12109","California-class");
insert into StarTrek_Schiffe values(257,"USS Rutledge","Unknown","Unknown");
insert into StarTrek_Schiffe values(258,"USS Sacramento","Unknown","Unknown");
insert into StarTrek_Schiffe values(259,"USS Salcombe","NCC-2107","Unknown");
insert into StarTrek_Schiffe values(260,"SS Santa Maria","BDR-529","Erewon-class personnel transport");
insert into StarTrek_Schiffe values(261,"USS Sarajevo","NCC-38529","Unknown");
insert into StarTrek_Schiffe values(262,"USS Saratoga","NCC-1887","Miranda-class");
insert into StarTrek_Schiffe values(263,"USS Saratoga","NCC-31911","Miranda-class");
insert into StarTrek_Schiffe values(264,"USS Sarek","Unknown","Unknown");
insert into StarTrek_Schiffe values(265,"USS Scovill","NCC-1598","Unknown");
insert into StarTrek_Schiffe values(266,"USS Seaquest","Unknown","Unknown");
insert into StarTrek_Schiffe values(267,"USS Seaview","Unknown","Unknown");
insert into StarTrek_Schiffe values(268,"USS Sentinel","Unknown","Unknown");
insert into StarTrek_Schiffe values(269,"USS Shenandoah","NCC-73024","Danube-class");
insert into StarTrek_Schiffe values(270,"USS Shenzhou","NCC-1227","Walker-class");
insert into StarTrek_Schiffe values(271,"USS Shepard","Unknown","Unknown");
insert into StarTrek_Schiffe values(272,"USS Sherlock Holmes","NCC-221B","Unknown");
insert into StarTrek_Schiffe values(273,"SS Shiku Maru","NBT-30894","Unknown");
insert into StarTrek_Schiffe values(274,"USS ShirKahr","NCC-31905","Miranda-class");
insert into StarTrek_Schiffe values(275,"USS Shran","NCC-1413","Magee-class");
insert into StarTrek_Schiffe values(276,"USS Silversides","Unknown","Unknown");
insert into StarTrek_Schiffe values(277,"USS Sioux","Unknown","Malachowski-class");
insert into StarTrek_Schiffe values(278,"USS Sitak","NCC-32591","Miranda-class");
insert into StarTrek_Schiffe values(279,"USS Solvang","NCC-12101","California-class");
insert into StarTrek_Schiffe values(280,"USS Springfield","NCC-1963","Unknown");
insert into StarTrek_Schiffe values(281,"USS Stargazer","NCC-2893","Constellation-class");
insert into StarTrek_Schiffe values(282,"Stella","Unknown","Class J starship");
insert into StarTrek_Schiffe values(283,"USS Strata","Unknown","Geoterraforming vessel");
insert into StarTrek_Schiffe values(284,"USS Suleiman","Unknown","Unknown");
insert into StarTrek_Schiffe values(285,"USS Sutherland","NCC-72015","Nebula-class");
insert into StarTrek_Schiffe values(286,"USS Syracuse","Unknown","Unknown");
insert into StarTrek_Schiffe values(287,"USS Tecumseh","NCC-14934","Unknown");
insert into StarTrek_Schiffe values(288,"USS Thomas Paine","NCC-65530","New Orleans-class");
insert into StarTrek_Schiffe values(289,"USS Thunderchild","NCC-63549","Akira-class");
insert into StarTrek_Schiffe values(290,"USS Tian An Men","NCC-21382","Miranda-class");
insert into StarTrek_Schiffe values(291,"USS Ticonderoga","NCC-87270","Unknown");
insert into StarTrek_Schiffe values(292,"USS Tikhov","NCC-1067-M","Unknown");
insert into StarTrek_Schiffe values(293,"USS Titan","NCC-80102","Luna-class");
insert into StarTrek_Schiffe values(294,"USS Tolstoy","Unknown","Unknown");
insert into StarTrek_Schiffe values(295,"USS Tombaugh","Unknown","Unknown");
insert into StarTrek_Schiffe values(296,"USS Trial","NCC-1948","Miranda-class");
insert into StarTrek_Schiffe values(297,"USS Trieste","NCC-37124","Merced-class");
insert into StarTrek_Schiffe values(298,"USS Tripoli","NCC-19386","Unknown");
insert into StarTrek_Schiffe values(299,"USS Truman","Unknown","Unknown");
insert into StarTrek_Schiffe values(300,"SS Tsiolkovsky","NCC-53911","Oberth-class");
insert into StarTrek_Schiffe values(301,"USS Tycho","NCC-85103","Unknown");
insert into StarTrek_Schiffe values(302,"USS Ulysses","Unknown","Unknown");
insert into StarTrek_Schiffe values(303,"USS Umibozu","Unknown","Unknown");
insert into StarTrek_Schiffe values(304,"USS Unicorn","NCC-85117","Unknown");
insert into StarTrek_Schiffe values(305,"USS Valdemar","Unknown","Unknown");
insert into StarTrek_Schiffe values(306,"USS Valiant","NCC-74210","Defiant-class");
insert into StarTrek_Schiffe values(307,"USS Valley Forge","NCC-43305","Excelsior-class");
insert into StarTrek_Schiffe values(308,"USS Vancouver","NCC-70492","Parliament-class");
insert into StarTrek_Schiffe values(309,"USS Vengeance","Unknown","Dreadnought-class");
insert into StarTrek_Schiffe values(310,"USS Venture","NCC-71854","Galaxy-class");
insert into StarTrek_Schiffe values(311,"USS Veracruz","Unknown","Unknown");
insert into StarTrek_Schiffe values(312,"SS Vico","NAR-18834","Oberth-class");
insert into StarTrek_Schiffe values(313,"USS Victory","NCC-9754","Constellation-class");
insert into StarTrek_Schiffe values(314,"USS Volga","Unknown","Danube-class");
insert into StarTrek_Schiffe values(315,"USS Voyager","NCC-74656","Intrepid-class");
insert into StarTrek_Schiffe values(316,"USS Voyager","NCC-74656-J","Intrepid-class");
insert into StarTrek_Schiffe values(317,"USS Wellington","NCC-33821","Unknown");
insert into StarTrek_Schiffe values(318,"USS White Sands","NAR-002","Unknown");
insert into StarTrek_Schiffe values(319,"USS Whorfin","NCC-1024","Unknown");
insert into StarTrek_Schiffe values(320,"SS Wisconsin","NAR-50732","Unknown");
insert into StarTrek_Schiffe values(321,"Woden","NCC-325","Antares-type");
insert into StarTrek_Schiffe values(322,"USS Wolcott","Unknown","Unknown");
insert into StarTrek_Schiffe values(323,"USS Wyoming","NCC-43730","Unknown");
insert into StarTrek_Schiffe values(324,"SS Xhosa","Unknown","Antares-class");
insert into StarTrek_Schiffe values(325,"USS Yamaguchi","NCC-26510","Ambassador-class");
insert into StarTrek_Schiffe values(326,"USS Yamato","NCC-71807","Galaxy-class");
insert into StarTrek_Schiffe values(327,"USS Yangtzee Kiang","Unknown","Danube-class");
insert into StarTrek_Schiffe values(328,"USS Yeager","NCC-1437","Cardenas-class");
insert into StarTrek_Schiffe values(329,"USS Yeager","NCC-61947","Saber-class");
insert into StarTrek_Schiffe values(330,"USS Yeager","NCC-65674","Yeager-type");
insert into StarTrek_Schiffe values(331,"USS Yellowstone","Unknown","Yellowstone-class");
insert into StarTrek_Schiffe values(332,"Yorkshire","NCC-330","Antares-type");
insert into StarTrek_Schiffe values(333,"USS Yorktown","NCC-20045","Unknown");
insert into StarTrek_Schiffe values(334,"USS Yosemite","NCC-19002","Oberth-class");
insert into StarTrek_Schiffe values(335,"USS Yukon","Unknown","Danube-class");
insert into StarTrek_Schiffe values(336,"USS Yuri Gagarin","NCC-25306","Unknown");
insert into StarTrek_Schiffe values(337,"USS Zapata","NCC-33184","Unknown");
insert into StarTrek_Schiffe values(338,"USS Zhukov","NCC-26136","Ambassador-class");

